#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

function beautify_js_by_folder {
  rootdir=$1
  echo "About to beautify under rootdir $rootdir"
  for f in $(find $rootdir -mindepth 1 -maxdepth 1 -type f -regex ".*\.js")
  do
    echo "  About to beautify $f"
    node $basedir/node_modules/esformatter/bin/esformatter --config "$basedir/esformatter_options.json" -i "$f" 
  done

  for d in $(find $rootdir -mindepth 1 -maxdepth 1 -type d)
  do
    if [[ $d =~ "/node_modules" || $d =~ "/bin" || $d =~ "/pugs" || $d =~ "/static" || $d =~ "/configs" || $d =~ "/transcoding_buffer" ]]; 
    then
      continue  
    fi
    echo "  About to beautify under depth 1 subdir $d"

    for f in $(find $d -mindepth 1 -type f -regex ".*\.js")
    do
      # Ignore files using "lazy/suspend pattern since React v16.6.0", https://reactjs.org/docs/code-splitting.html#reactlazy.
      if [[ $f =~ "/index.js" || $f =~ "/landing.js" ]]; 
      then
        continue  
      fi
      echo "    About to beautify $f"
      node $basedir/node_modules/esformatter/bin/esformatter --config "$basedir/esformatter_options.json" -i "$f" 
    done
  done 
}

target_rootdirs=( "$basedir/common" "$basedir/backend" "$basedir/frontend" )

for rootdir in "${target_rootdirs[@]}"
do
  beautify_js_by_folder $rootdir 
done

