#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

function beautify_js_by_folder {
  root_folder=$1
  echo "About to beautify under $root_folder"
  node $basedir/node_modules/esformatter/bin/esformatter -i "$root_folder/*.js" 
  for d in $(find $root_folder -mindepth 1 -maxdepth 1 -type d)
  do
    if [[ $d =~ "/node_modules" || $d =~ "/bin" || $d =~ "/pugs" || $d =~ "/static" || $d =~ "/configs" || $d =~ "/transcoding_buffer" ]]; 
    then
      continue  
    fi
    echo "About to beautify under $d"
    # Ignore files using "lazy/suspend pattern since React v16.6.0", https://reactjs.org/docs/code-splitting.html#reactlazy.
    node $basedir/node_modules/esformatter/bin/esformatter --config "$basedir/esformatter_options.json" --ignore "$d/**/index.js" --ignore "$d/**/landing.js" -i "$d/**/*.js" 
  done 
}

target_root_folders=( "$basedir/common" "$basedir/backend" "$basedir/frontend" )

for root_folder in "${target_root_folders[@]}"
do
  beautify_js_by_folder $root_folder 
done

